/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author achala
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
     public Main() {
        initComponents();
    }
     
     
     int ID_1;
     
     int newid;
     String newusername;
     String newusertype;
     String Utype;
     
    public Main(int ID,String username,String usertype) {
        initComponents();
        
        this.newusername = username;
        jLabel1.setText(newusername);
        
        this.newusertype = usertype;
        jLabel2.setText(newusertype);
        
        this.newid = ID;
        
        
        ID_1 = newid;
        
        Utype = jLabel2.getText();
        

           
        
        if(Utype == "Doctor"){
            patientbtn1.setVisible(false);
            CreateCHbtn.setVisible(false);
            ViewPRIbtn1.setVisible(false);
            CreateITEMbtn1.setVisible(false);
            CreateUSERbtn1.setVisible(false);
            ViewDOCbtn1.setVisible(false);
            
        }
        else if(Utype == "Receptionist"){
            doctorbtn1.setVisible(false);
            ViewCHbtn.setVisible(false);
            ViewDOCbtn1.setVisible(false);
        }
        
        else if(Utype == "Pharmacist"){
            patientbtn1.setVisible(false);
            doctorbtn1.setVisible(false);
            CreateCHbtn.setVisible(false);
            ViewCHbtn.setVisible(false);
            CreateUSERbtn1.setVisible(false);
            ViewDOCbtn1.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patient = new javax.swing.JPanel();
        CreateCHbtn = new javax.swing.JButton();
        patientbtn1 = new javax.swing.JButton();
        doctorbtn1 = new javax.swing.JButton();
        ViewCHbtn = new javax.swing.JButton();
        ViewDOCbtn = new javax.swing.JButton();
        ViewPRIbtn1 = new javax.swing.JButton();
        CreateITEMbtn1 = new javax.swing.JButton();
        CreateUSERbtn1 = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Usernamebar = new javax.swing.JLabel();
        Usertypebar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewDOCbtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Channel Center");

        patient.setBackground(new java.awt.Color(255, 204, 204));

        CreateCHbtn.setText("Create Channel");
        CreateCHbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCHbtnActionPerformed(evt);
            }
        });

        patientbtn1.setText("Patient");
        patientbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbtn1ActionPerformed(evt);
            }
        });

        doctorbtn1.setText("Doctor");
        doctorbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbtn1ActionPerformed(evt);
            }
        });

        ViewCHbtn.setText("View Channel");
        ViewCHbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCHbtnActionPerformed(evt);
            }
        });

        ViewDOCbtn.setText("View Doctor");
        ViewDOCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDOCbtnActionPerformed(evt);
            }
        });

        ViewPRIbtn1.setText("View Prescription");
        ViewPRIbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPRIbtn1ActionPerformed(evt);
            }
        });

        CreateITEMbtn1.setText("Create Item");
        CreateITEMbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateITEMbtn1ActionPerformed(evt);
            }
        });

        CreateUSERbtn1.setText("Create User");
        CreateUSERbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUSERbtn1ActionPerformed(evt);
            }
        });

        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientLayout = new javax.swing.GroupLayout(patient);
        patient.setLayout(patientLayout);
        patientLayout.setHorizontalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateUSERbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateITEMbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewDOCbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewCHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateCHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewPRIbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        patientLayout.setVerticalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(patientbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doctorbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateCHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ViewCHbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewPRIbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateITEMbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateUSERbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewDOCbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        Usernamebar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Usernamebar.setText("User Name");

        Usertypebar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Usertypebar.setText("User Type");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("jLabel2");

        ViewDOCbtn1.setText("View Doctor");
        ViewDOCbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDOCbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usernamebar)
                    .addComponent(Usertypebar))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewDOCbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usernamebar)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usertypebar)
                    .addComponent(jLabel2))
                .addGap(97, 97, 97)
                .addComponent(ViewDOCbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("Chanel Center");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCHbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCHbtnActionPerformed
        // TODO add your handling code here:
        Channel ch = new Channel();
        ch.setVisible(true);
    }//GEN-LAST:event_CreateCHbtnActionPerformed

    private void patientbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbtn1ActionPerformed
        // TODO add your handling code here:
        
        Patient p = new Patient();
        p.setVisible(true);
        
    }//GEN-LAST:event_patientbtn1ActionPerformed

    private void doctorbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbtn1ActionPerformed
        // TODO add your handling code here:
        
        
         if(Utype == "Doctor"){
             new Doctor(ID_1,Utype).setVisible(true);
             
         }
        
        
        
      
    }//GEN-LAST:event_doctorbtn1ActionPerformed

    private void ViewCHbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCHbtnActionPerformed
        // TODO add your handling code here:
        
        new ViewChannel(ID_1).setVisible(true);
        
        
        
    }//GEN-LAST:event_ViewCHbtnActionPerformed

    private void ViewDOCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDOCbtnActionPerformed
        // TODO add your handling code here:





        ViewDoctor vd = new ViewDoctor();
        vd.setVisible(true);





    }//GEN-LAST:event_ViewDOCbtnActionPerformed

    private void ViewPRIbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPRIbtn1ActionPerformed
        // TODO add your handling code here:
        viewPrescription p = new viewPrescription();
        p.setVisible(true);
    }//GEN-LAST:event_ViewPRIbtn1ActionPerformed

    private void CreateITEMbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateITEMbtn1ActionPerformed
        // TODO add your handling code here:
        Item i = new Item();
        i.setVisible(true);
        
        
    }//GEN-LAST:event_CreateITEMbtn1ActionPerformed

    private void CreateUSERbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUSERbtn1ActionPerformed
        // TODO add your handling code here:
        
        User u = new User();
        u.setVisible(true);
    }//GEN-LAST:event_CreateUSERbtn1ActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        
        Login l = new Login();
        this.setVisible(false);
        l.setVisible(true);
        
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void ViewDOCbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDOCbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewDOCbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCHbtn;
    private javax.swing.JButton CreateITEMbtn1;
    private javax.swing.JButton CreateUSERbtn1;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel Usernamebar;
    private javax.swing.JLabel Usertypebar;
    private javax.swing.JButton ViewCHbtn;
    private javax.swing.JButton ViewDOCbtn;
    private javax.swing.JButton ViewDOCbtn1;
    private javax.swing.JButton ViewPRIbtn1;
    private javax.swing.JButton doctorbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel patient;
    private javax.swing.JButton patientbtn1;
    // End of variables declaration//GEN-END:variables
}
